vlog -work work D:/Documentos/Designs/Quartus/AES/simulation/modelsim/Waveform.vwf.vt
vsim -novopt -c -t 1ps -L cycloneiii_ver -L altera_ver -L altera_mf_ver -L 220model_ver -L sgate work.topo_vlg_vec_tst
onerror {resume}
add wave {topo_vlg_vec_tst/i1/clk_m}
add wave {topo_vlg_vec_tst/i1/reset_m}
add wave {topo_vlg_vec_tst/i1/chipher}
add wave {topo_vlg_vec_tst/i1/chipher[127]}
add wave {topo_vlg_vec_tst/i1/chipher[126]}
add wave {topo_vlg_vec_tst/i1/chipher[125]}
add wave {topo_vlg_vec_tst/i1/chipher[124]}
add wave {topo_vlg_vec_tst/i1/chipher[123]}
add wave {topo_vlg_vec_tst/i1/chipher[122]}
add wave {topo_vlg_vec_tst/i1/chipher[121]}
add wave {topo_vlg_vec_tst/i1/chipher[120]}
add wave {topo_vlg_vec_tst/i1/chipher[119]}
add wave {topo_vlg_vec_tst/i1/chipher[118]}
add wave {topo_vlg_vec_tst/i1/chipher[117]}
add wave {topo_vlg_vec_tst/i1/chipher[116]}
add wave {topo_vlg_vec_tst/i1/chipher[115]}
add wave {topo_vlg_vec_tst/i1/chipher[114]}
add wave {topo_vlg_vec_tst/i1/chipher[113]}
add wave {topo_vlg_vec_tst/i1/chipher[112]}
add wave {topo_vlg_vec_tst/i1/chipher[111]}
add wave {topo_vlg_vec_tst/i1/chipher[110]}
add wave {topo_vlg_vec_tst/i1/chipher[109]}
add wave {topo_vlg_vec_tst/i1/chipher[108]}
add wave {topo_vlg_vec_tst/i1/chipher[107]}
add wave {topo_vlg_vec_tst/i1/chipher[106]}
add wave {topo_vlg_vec_tst/i1/chipher[105]}
add wave {topo_vlg_vec_tst/i1/chipher[104]}
add wave {topo_vlg_vec_tst/i1/chipher[103]}
add wave {topo_vlg_vec_tst/i1/chipher[102]}
add wave {topo_vlg_vec_tst/i1/chipher[101]}
add wave {topo_vlg_vec_tst/i1/chipher[100]}
add wave {topo_vlg_vec_tst/i1/chipher[99]}
add wave {topo_vlg_vec_tst/i1/chipher[98]}
add wave {topo_vlg_vec_tst/i1/chipher[97]}
add wave {topo_vlg_vec_tst/i1/chipher[96]}
add wave {topo_vlg_vec_tst/i1/chipher[95]}
add wave {topo_vlg_vec_tst/i1/chipher[94]}
add wave {topo_vlg_vec_tst/i1/chipher[93]}
add wave {topo_vlg_vec_tst/i1/chipher[92]}
add wave {topo_vlg_vec_tst/i1/chipher[91]}
add wave {topo_vlg_vec_tst/i1/chipher[90]}
add wave {topo_vlg_vec_tst/i1/chipher[89]}
add wave {topo_vlg_vec_tst/i1/chipher[88]}
add wave {topo_vlg_vec_tst/i1/chipher[87]}
add wave {topo_vlg_vec_tst/i1/chipher[86]}
add wave {topo_vlg_vec_tst/i1/chipher[85]}
add wave {topo_vlg_vec_tst/i1/chipher[84]}
add wave {topo_vlg_vec_tst/i1/chipher[83]}
add wave {topo_vlg_vec_tst/i1/chipher[82]}
add wave {topo_vlg_vec_tst/i1/chipher[81]}
add wave {topo_vlg_vec_tst/i1/chipher[80]}
add wave {topo_vlg_vec_tst/i1/chipher[79]}
add wave {topo_vlg_vec_tst/i1/chipher[78]}
add wave {topo_vlg_vec_tst/i1/chipher[77]}
add wave {topo_vlg_vec_tst/i1/chipher[76]}
add wave {topo_vlg_vec_tst/i1/chipher[75]}
add wave {topo_vlg_vec_tst/i1/chipher[74]}
add wave {topo_vlg_vec_tst/i1/chipher[73]}
add wave {topo_vlg_vec_tst/i1/chipher[72]}
add wave {topo_vlg_vec_tst/i1/chipher[71]}
add wave {topo_vlg_vec_tst/i1/chipher[70]}
add wave {topo_vlg_vec_tst/i1/chipher[69]}
add wave {topo_vlg_vec_tst/i1/chipher[68]}
add wave {topo_vlg_vec_tst/i1/chipher[67]}
add wave {topo_vlg_vec_tst/i1/chipher[66]}
add wave {topo_vlg_vec_tst/i1/chipher[65]}
add wave {topo_vlg_vec_tst/i1/chipher[64]}
add wave {topo_vlg_vec_tst/i1/chipher[63]}
add wave {topo_vlg_vec_tst/i1/chipher[62]}
add wave {topo_vlg_vec_tst/i1/chipher[61]}
add wave {topo_vlg_vec_tst/i1/chipher[60]}
add wave {topo_vlg_vec_tst/i1/chipher[59]}
add wave {topo_vlg_vec_tst/i1/chipher[58]}
add wave {topo_vlg_vec_tst/i1/chipher[57]}
add wave {topo_vlg_vec_tst/i1/chipher[56]}
add wave {topo_vlg_vec_tst/i1/chipher[55]}
add wave {topo_vlg_vec_tst/i1/chipher[54]}
add wave {topo_vlg_vec_tst/i1/chipher[53]}
add wave {topo_vlg_vec_tst/i1/chipher[52]}
add wave {topo_vlg_vec_tst/i1/chipher[51]}
add wave {topo_vlg_vec_tst/i1/chipher[50]}
add wave {topo_vlg_vec_tst/i1/chipher[49]}
add wave {topo_vlg_vec_tst/i1/chipher[48]}
add wave {topo_vlg_vec_tst/i1/chipher[47]}
add wave {topo_vlg_vec_tst/i1/chipher[46]}
add wave {topo_vlg_vec_tst/i1/chipher[45]}
add wave {topo_vlg_vec_tst/i1/chipher[44]}
add wave {topo_vlg_vec_tst/i1/chipher[43]}
add wave {topo_vlg_vec_tst/i1/chipher[42]}
add wave {topo_vlg_vec_tst/i1/chipher[41]}
add wave {topo_vlg_vec_tst/i1/chipher[40]}
add wave {topo_vlg_vec_tst/i1/chipher[39]}
add wave {topo_vlg_vec_tst/i1/chipher[38]}
add wave {topo_vlg_vec_tst/i1/chipher[37]}
add wave {topo_vlg_vec_tst/i1/chipher[36]}
add wave {topo_vlg_vec_tst/i1/chipher[35]}
add wave {topo_vlg_vec_tst/i1/chipher[34]}
add wave {topo_vlg_vec_tst/i1/chipher[33]}
add wave {topo_vlg_vec_tst/i1/chipher[32]}
add wave {topo_vlg_vec_tst/i1/chipher[31]}
add wave {topo_vlg_vec_tst/i1/chipher[30]}
add wave {topo_vlg_vec_tst/i1/chipher[29]}
add wave {topo_vlg_vec_tst/i1/chipher[28]}
add wave {topo_vlg_vec_tst/i1/chipher[27]}
add wave {topo_vlg_vec_tst/i1/chipher[26]}
add wave {topo_vlg_vec_tst/i1/chipher[25]}
add wave {topo_vlg_vec_tst/i1/chipher[24]}
add wave {topo_vlg_vec_tst/i1/chipher[23]}
add wave {topo_vlg_vec_tst/i1/chipher[22]}
add wave {topo_vlg_vec_tst/i1/chipher[21]}
add wave {topo_vlg_vec_tst/i1/chipher[20]}
add wave {topo_vlg_vec_tst/i1/chipher[19]}
add wave {topo_vlg_vec_tst/i1/chipher[18]}
add wave {topo_vlg_vec_tst/i1/chipher[17]}
add wave {topo_vlg_vec_tst/i1/chipher[16]}
add wave {topo_vlg_vec_tst/i1/chipher[15]}
add wave {topo_vlg_vec_tst/i1/chipher[14]}
add wave {topo_vlg_vec_tst/i1/chipher[13]}
add wave {topo_vlg_vec_tst/i1/chipher[12]}
add wave {topo_vlg_vec_tst/i1/chipher[11]}
add wave {topo_vlg_vec_tst/i1/chipher[10]}
add wave {topo_vlg_vec_tst/i1/chipher[9]}
add wave {topo_vlg_vec_tst/i1/chipher[8]}
add wave {topo_vlg_vec_tst/i1/chipher[7]}
add wave {topo_vlg_vec_tst/i1/chipher[6]}
add wave {topo_vlg_vec_tst/i1/chipher[5]}
add wave {topo_vlg_vec_tst/i1/chipher[4]}
add wave {topo_vlg_vec_tst/i1/chipher[3]}
add wave {topo_vlg_vec_tst/i1/chipher[2]}
add wave {topo_vlg_vec_tst/i1/chipher[1]}
add wave {topo_vlg_vec_tst/i1/chipher[0]}
add wave {topo_vlg_vec_tst/i1/round_m}
add wave {topo_vlg_vec_tst/i1/round_m[3]}
add wave {topo_vlg_vec_tst/i1/round_m[2]}
add wave {topo_vlg_vec_tst/i1/round_m[1]}
add wave {topo_vlg_vec_tst/i1/round_m[0]}
add wave {topo_vlg_vec_tst/i1/en_c}
add wave {topo_vlg_vec_tst/i1/en_r}
add wave {topo_vlg_vec_tst/i1/en_t}
add wave {topo_vlg_vec_tst/i1/sel_m}
add wave {topo_vlg_vec_tst/i1/sel_m3}
add wave {topo_vlg_vec_tst/i1/state}
add wave {topo_vlg_vec_tst/i1/state[2]}
add wave {topo_vlg_vec_tst/i1/state[1]}
add wave {topo_vlg_vec_tst/i1/state[0]}
add wave {topo_vlg_vec_tst/i1/en_ra}
run -all
